version: "3.8"
services:
  frontend:
    image: ynwoo/tunemate-front-dev:latest
    build:
      context: ./FE
  backend:
    image: ynwoo/tunemate-user:latest
    build:
      context: ./tunemate-user-service
      dockerfile: Dockerfile