version: '3.8'
services:
  backend:
    image: ynwoo/tunemate-music:latest
    build:
      context: ./tunemate-playlist
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
