version: '3.8'
services:
  backend:
    image: ynwoo/tunemate-recommend:latest
    build:
      context: ./tunemate-recommend-service
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
