server:
  port: ${gateway-server-port}
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/login/oauth2/**
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /$\{segment}
        - id: user-service-authorization
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/oauth2/authorization/**
          filters:
            - RewritePath=/api/v1/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/users/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/api/v1/user-service/(?<segment>.*), /$\{segment}
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/v1/music-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/api/v1/music-service/(?<segment>.*), /$\{segment}
        - id: social-service
          uri: lb://social-service
          predicates:
            - Path=/api/v1/social-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/api/v1/social-service/(?<segment>.*), /$\{segment}
        - id: recommend-service
          uri: lb://recommendation-service
          predicates:
            - Path=/api/v1/recommendation-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/api/v1/recommendation-service/(?<segment>.*), /$\{segment}
      default-filters:
        - name: GlobalFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka-service-url}

jwt:
  private-key: ${jwt-private-key}
  access-token:
    expiration-epoch: 7200000 # 2 hours