server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka-service-url}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}

logging:
  level:
    com.example.com.example.tunemateuserservice: debug