spring:
  application:
    name: music-service
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    hikari:
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

spotify:
  base-url: https://api.spotify.com/v1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance.id:${random.value}}

server:
  port: 0

logging:
  level:
    com.tunemate.tunemateplaylist: debug